version: '3.8'
services:
  acme-keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    user: "1000:1000"
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
#      KEYCLOAK_USER: "admin"
#      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "h2"
      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"

# Exposes Metrics via http://localhost:9990/metrics
      KEYCLOAK_STATISTICS: all

#      KEYCLOAK_IMPORT: "/opt/jboss/imex/custom-realm.json"
# use `docker-compose --env-file custom-keycloak.env up` to populate the KEYCLOAK_CONFIG_FILE variable.
    command: [ "--debug", "*:8787", "--server-config", "$KEYCLOAK_CONFIG_FILE", "-b" , "0.0.0.0", "-bmanagement" , "0.0.0.0", "-Dwildfly.statistics-enabled=true"]
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "127.0.0.1:8787:8787"
    volumes:
      - ./keycloak/extensions/target/classes:/opt/jboss/keycloak/standalone/deployments/extensions.jar:z
      - ./keycloak/themes/apps:/opt/jboss/keycloak/themes/apps:z
      - ./keycloak/themes/internal:/opt/jboss/keycloak/themes/internal:z
      - ./keycloak/config/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties:z
      - ./keycloak/imex:/opt/jboss/imex:z
# This will exposes *.sh and *.cli startup scripts that are executed by Keycloak.
      - ./keycloak/cli:/opt/jboss/startup-scripts:z
      - ./testrun/data:/opt/jboss/keycloak/standalone/data:z

  acme-keycloak-provisioning:
    image: adorsys/keycloak-config-cli:v3.4.0-13.0.0
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      IMPORT_PATH: "/config"
      IMPORT_FORCE: "false"
      IMPORT_VARSUBSTITUTION: "true"
    volumes:
      - ./config/stage/dev/realms:/config:z

  mailhog:
    # Web Interface: http://localhost:1080/#
    # Web API: http://localhost:1080/api/v2/messages
    # mailhog/mailhog:v1.0.1
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    logging:
      driver: none
    ports:
      - "1080:8025"
      - "1025:1025"

  openldap:
    image: osixia/openldap:1.5.0
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
#      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Acme Inc."
      LDAP_DOMAIN: "corp.acme.local"
      LDAP_BASE_DN: ""
      # admin User: cn=admin,dc=corp,dc=acme,dc=local
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_SEED_INTERNAL_LDIF_PATH: "/acme/openldap/ldif/10-bootstrap.ldif"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
      - ./config/stage/dev/openldap/demo.ldif:/acme/openldap/ldif/10-bootstrap.ldif:z
    ports:
      - "1389:389"
      - "1636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "demo.local"
    hostname: "ldap1"
    command: [ "--copy-service", "--loglevel", "debug" ]

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "17080:80"
    depends_on:
      - openldap

  acme-app-oidc-js-spa:
    image: httpd:2.4
    volumes:
      - ./apps/oidc-js-spa/htdocs:/usr/local/apache2/htdocs/:z
    ports:
      - "4000:80"
      - "4443:443"
