services:

  acme-keycloak-1:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: https://id.acme.test:4443/auth
    # IntelliJ currently does not support the depends_on condition syntax
    depends_on:
      acme-keycloak-db:
        condition: service_healthy


  acme-keycloak-2:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: https://id.acme.test:4443/auth
    # IntelliJ currently does not support the depends_on condition syntax
    depends_on:
      acme-keycloak-db:
        condition: service_healthy

  acme-keycloak-db:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak-db

  acme-envoy-lb:
    image: envoyproxy/envoy-alpine:v1.18.3
#    logging:
#      driver: none
    environment:
      ENVOY_UID: 1000
      ENVOY_GID: 1000
    volumes:
      # relative paths needs to be relative to the docker-compose cwd.
      - ./envoy.yaml:/etc/envoy/envoy.yaml:z
#      - ./dhparams:/etc/ssl/dhparams:z
      - ../../../../config/stage/dev/tls/acme.test+1.pem:/etc/envoy/cert.pem:z
      - ../../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/envoy/key.pem:z
    ports:
      - "4443:4443"
    command:
      - "--config-path"
      - "/etc/envoy/envoy.yaml"
      - "--service-cluster"
      - "keycloak_cluster"
    depends_on:
      - acme-keycloak-1
      - acme-keycloak-2
