spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - https://localhost:${server.port}

com:
  c4-soft:
    springaddons:
      security:
        issuers:
          - location: https://localhost:8443/auth/realms/acme-internal
            username-claim: preferred_username
            authorities:
              claims:
                - realm_access.roles
                - resource_access.spring-addons-confidential.roles
              caze: UPPER
              prefix: ROLE_
        cors:
        - path: "/api/**"
          allowed-origins: "https://localhost:4443"
        permit-all: 

server:
  port: 4623
  ssl:
    enabled: true
    key-store: ../../config/stage/dev/tls/acme.test+1.p12
    key-store-password: changeit