realm: acme-workshop
identityProviders:
  - alias: "Google"
    displayName: "Acme Google Login"
    providerId: "google"
    enabled: false
    updateProfileFirstLoginMode: on
    trustEmail: true
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    firstBrokerLoginFlowAlias: "first broker login"
    #    postBrokerLoginFlowAlias: "Custom Post Broker Login"
    config:
      guiOrder: "5000"
      syncMode: IMPORT
      userIp: true
      clientSecret: dummysecret
      clientId: dummyclientid
      useJwksUrl: true