realm: acme-internal
#identityProviders:
#  - alias: "idp-acme-azuread"
#    displayName: "Acme EntraID Login"
#    providerId: "oidc"
#    enabled: true
#    updateProfileFirstLoginMode: on
#    trustEmail: true
#    storeToken: false
#    addReadTokenRoleOnCreate: false
#    authenticateByDefault: false
#    linkOnly: false
#    firstBrokerLoginFlowAlias: "first broker login"
#  #    postBrokerLoginFlowAlias: "Custom Post Broker Login"
#    config:
#      guiOrder: "4000"
#      issuer: "$(env:ACME_AZURE_AAD_TENANT_URL)/v2.0"
#      tokenUrl: "$(env:ACME_AZURE_AAD_TENANT_URL)/oauth2/v2.0/token"
#      jwksUrl: "$(env:ACME_AZURE_AAD_TENANT_URL)/discovery/v2.0/keys"
#      userInfoUrl: "https://graph.microsoft.com/oidc/userinfo"
#      authorizationUrl: "$(env:ACME_AZURE_AAD_TENANT_URL)/oauth2/v2.0/authorize"
#      logoutUrl: "$(env:ACME_AZURE_AAD_TENANT_URL)/oauth2/v2.0/logout"
#      clientId: "$(env:ACME_AZURE_AAD_TENANT_CLIENT_ID:-dummy)"
#      clientSecret: "$(env:ACME_AZURE_AAD_TENANT_CLIENT_SECRET:-secret)"
#      clientAuthMethod: "client_secret_post"
#      defaultScope: "openid profile email"
#      loginHint: "true"
#      backchannelSupported: "true"
#      validateSignature: "true"
#      useJwksUrl: "true"
#      syncMode: "FORCE"