realm: acme-user-profile
enabled: true

attributes:
  userProfileEnabled: true

userProfile:
  attributes:
    - name: username
      displayName: "${username}"
      validations:
        length:
          min: 3
          max: 255
    - name: email
      displayName: "${email}"
      validations:
        length:
          max: 255
    - name: firstName
      displayName: "${firstName}"
      required:
        roles:
          - user
      permissions:
        view:
          - admin
          - user
        edit:
          - admin
          - user
      validations:
        length:
          max: 255
    - name: lastName
      displayName: "${lastName}"
      required:
        roles:
          - user
      permissions:
        view:
          - admin
          - user
        edit:
          - admin
          - user
      validations:
        length:
          max: 255
    - name: phoneNumber
      displayName: "${phoneNumber}"
      annotations:
        inputType: "html5-tel"
      validations:
        length:
          min: 6
          max: 64
      required:
        roles:
          - user
        scopes:
          - "phone"
      selector:
        scopes: [ "phone" ]
      permissions:
        view:
          - user
          - admin
        edit:
          - user
          - admin