realm: acme-user-profile
enabled: true

components:
  "org.keycloak.userprofile.UserProfileProvider":
    - name: "Acme User Profile"
      providerId: "declarative-user-profile"
      config:
        attributes:
          - name: username
            displayName: "${username}"
            validations:
              length:
                min: 3
                max: 255
          - name: email
            displayName: "${email}"
            validations:
              length:
                max: 255
          - name: firstName
            displayName: "${firstName}"
            required:
              roles:
                - user
            permissions:
              view:
                - admin
                - user
              edit:
                - admin
                - user
            validations:
              length:
                max: 255
          - name: lastName
            displayName: "${lastName}"
            required:
              roles:
                - user
            permissions:
              view:
                - admin
                - user
              edit:
                - admin
                - user
            validations:
              length:
                max: 255
          - selector:
              scopes: [ ]
            permissions:
              view:
                - user
                - admin
              edit:
                - user
                - admin
            name: phoneNumber
            displayName: "${phoneNumber}"
