services:

  acme-keycloakx:
    build:
      context: "./keycloakx"
      dockerfile: "./Dockerfile"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: acme-keycloak-db
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public

      # Enable remote debugging
      DEBUG: "true"
      DEBUG_PORT: "*:8787"

#      KC_CACHE: local

      # uses keycloakx/cache-custom.xml
      #KC_CACHE: cache-custom.xml
      KC_CACHE_CONFIG_FILE: cache-custom-jgroups.xml

# Workaround for missing postgres JDBC driver for JDBC Ping
#      JAVA_OPTS_APPEND: "-Xbootclasspath/a:/opt/keycloak/lib/lib/main/org.postgresql.postgresql-42.3.1.jar"

# Default JAVA_OPTS
      #JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
      JAVA_OPTS: "-XX:MaxRAMPercentage=80 -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+DisableExplicitGC -Djava.net.preferIPv4Stack=true"

      # Allow access via visualvm and jmc
      JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8790 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

    volumes:
      # This configures the key and certificate for HTTPS.
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/https/tls.crt:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/x509/https/tls.key:z
      # Allow TLS connection to ourselves, this is necessary for cross realm Identity Brokering
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/ca/tls.crt:z
    command:
      - "--verbose"
      - "start"
      - "--https-certificate-file=/etc/x509/https/tls.crt"
      - "--https-certificate-key-file=/etc/x509/https/tls.key"
      - "--http-enabled=true"
      - "--http-relative-path=/auth"
      - "--http-port=8080"
      - "--proxy=passthrough"
# Note upcoming versions of Keycloak.X will leave out the port in the hostname parameter
      - "--hostname=id.acme.test:1443"

    ports:
      - "8080"
      - "8443"
      - "8787"
      - "8790"

  acme-keycloak-db:
    image: postgres:11.12
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./run/postgres/data:/var/lib/postgresql/data:z
