realm: acme-client-examples
enabled: true

clients:
  - clientId: acme-client-spa-app
    protocol: openid-connect
    name: Acme SPA Frontend App
    description: "JavaScript based Single-Page App as Public Client that uses Authorization Code Grant Flow"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    rootUrl: "https://www.keycloak.org/app"
    baseUrl: "/#url=https://id.acme.test:8443/auth&realm=acme-client-examples&client=acme-client-spa-app"
    adminUrl: ""
    redirectUris:
      - "/*"
      - "https://flowsimulator.pragmaticwebsecurity.com"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - clientId: acme-client-cli-app
    protocol: openid-connect
    name: Acme CLI App
    description: "Command-line interface app that can obtain tokens with Username + Password and ClientId via grant_type=password"
    enabled: true
    publicClient: true
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
    attributes:
      "use.refresh.tokens": "false"

  - clientId: acme-client-classic-web-app
    protocol: openid-connect
    name: Acme Classic Server-side Web Application
    description: "Classic Server-side Web Application that uses Authorization Code Grant Flow"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false
    secret: "$(env:ACME_APPS_APP_WEB_SPRINGBOOT_SECRET:-secret)"
    fullScopeAllowed: false
    rootUrl: "https://apps.acme.test:4633/webapp"
    baseUrl: "/"
    adminUrl: ""
    redirectUris:
      - "/*"
      - "https://flowsimulator.pragmaticwebsecurity.com"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - clientId: acme-client-legacy-app
    protocol: openid-connect
    name: Acme Legacy App
    description: "Legacy App that can obtain tokens with Username + Password and ClientId+Secret via grant_type=password"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    secret: "$(env:ACME_CLIENT_EXAMPLES_CLIENT_SECRET:-secret)"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"

  - clientId: acme-client-api-resource-server
    protocol: openid-connect
    name: Acme API Resource Server
    description: "OAuth2 Resource Server that can be called with an AccessToken, can be used to provide Role configuration for an API"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false

  - clientId: acme-client-api-resource-server2
    protocol: openid-connect
    name: Acme API Resource Server 2
    description: "OAuth2 Resource Server that can be called with an AccessToken, can be used to provide Role configuration for an API"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false


  - clientId: acme-client-service-app
    protocol: openid-connect
    name: Acme Service App
    description: "Acme Service App that can obtain tokens via grant_type=client_credentials"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    secret: "$(env:ACME_CLIENT_EXAMPLES_CLIENT_SECRET:-secret)"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"

  - clientId: acme-client-mobile-app
    protocol: openid-connect
    name: Acme Mobile App
    description: "Acme Mobile App with Authorization Code Flow"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    #    attributes: { }
    fullScopeAllowed: false
    redirectUris:
      # App URL
      - "acme://app/callback/*"
      # Claimed URL
      - "https://mobile.acme.test/*"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
      - "offline_access"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - clientId: acme-client-desktop-app
    protocol: openid-connect
    name: Acme Desktop App
    description: "Acme Desktop App with Authorization Code Flow"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/*"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
      - "offline_access"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - clientId: acme-client-idp-broker-oidc
    protocol: openid-connect
    name: Acme OIDC IDP Broker
    description: "Client for OpenID Connect Identity Provider"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    fullScopeAllowed: false
    secret: "$(env:ACME_APPS_INTERNAL_IDP_BROKER_SECRET:-secret)"
    redirectUris:
      - "$(env:KEYCLOAK_FRONTEND_URL)/realms/acme-apps/broker/idp-acme-internal/endpoint/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"

  - clientId: acme-client-saml-webapp
    name: "Acme Classical Web App SAML"
    description: "Classical Web App which use SAML for SSO"
    rootUrl: 'https://apps.acme.test:4723'
    adminUrl: "/saml"
    baseUrl: "/"
    surrogateAuthRequired: false
    enabled: true
    alwaysDisplayInConsole: false
    clientAuthenticatorType: client-secret
    redirectUris:
      - "/saml/consume"
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: true
    protocol: saml
    attributes:
      "saml.force.post.binding": "true"
      "saml.multivalued.roles": "false"
      "frontchannel.logout.session.required": "false"
      "saml.server.signature.keyinfo.ext": "false"
      # TODO externalize saml certificate
      saml.signing.certificate: "MIIEFTCCAn2gAwIBAgIQCSD0cM/czR4Rb3t/5MesJTANBgkqhkiG9w0BAQsFADBTMR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExFDASBgNVBAsMC3RvbUBuZXVtYW5uMRswGQYDVQQDDBJta2NlcnQgdG9tQG5ldW1hbm4wHhcNMjIwMTE5MTA1NDIyWhcNMzIwMTE5MTA1NDIyWjA/MScwJQYDVQQKEx5ta2NlcnQgZGV2ZWxvcG1lbnQgY2VydGlmaWNhdGUxFDASBgNVBAsMC3RvbUBuZXVtYW5uMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtWoSr1BEpMy64BsaVGXyKCpz1qtoqX4lC0LPghE2xz+N88HJIAB60//pmkoYi++Yg7EvaN6/R6saFWQ4l3KTrAKdqZnBc5ylFwMDk5aeNdqnycnMq4tYIIZ5Kd5ATHexsQ5BI5MgDrGa65uR8yU/D8FSTEhEXBMUOCPTmaz/eDccHnmx2wa17zDoBabeCpUnRGzuvX+YtyYi7VlAq9cf1PHjr7YQeXpocwZSifOJn0FrNItHfTeGrYZbcCe9IUY07T2g3Jd2kbgra8V5XFau0cxGqQYq4IwqpuIiVKas7xs6Y5mmLMz1slfSavmGwJOXg+U9ZqpquI4kyc2jHN6kvQIDAQABo3kwdzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTvbKPnxrx5ICZChpVluUL4O+etgDAhBgNVHREEGjAYgglhY21lLnRlc3SCCyouYWNtZS50ZXN0MA0GCSqGSIb3DQEBCwUAA4IBgQBjYKjLhBfbovY1bJrn7KJ1cirOUQ7PZpHBCxWUy4pkQYveGYLNJbEMdFV7zfMPlNrusz5Roqporz09sX3L6T1PAYkXBEDLIYJArB1nUjrAt36oNvY5wO9wgnJUJlMO3rxVsk3vivG1zf8PPXAq/U6fF+lHbm9VNxhGn9HMQb7ahNVW7S980ioRvZta1vrBX56ItY5WLOTnb9hcrXmN+Y8c9sh6vUbxGcXpXhMC5l55aCgLCxOS/qJAT/G7sBHoPKNk4h33T0wehkCCLjO19QvBQI2eCUAWJnAE7Hv8L22IuoSpLUDfPoN9nq4gMcqyyAq7WqS4MAMwZjLAM7IMS17wQX/B0pzBZPgE5/ankTEhDH710Ct5of3bizIEd/oOSwBqotIVOVx1XX5NzEI3HCIeYj8TAIlp1k32yYqqJTOkD7dFgKIY8VvZqJXU8iQ/dVSbaHodmuyAlabjeXcXPABFCr/5Vc+TpngiZT8tDfY1hPUKJmKSl+gp71Y1WYDWKH0="
      "backchannel.logout.session.required": "false"
      "saml.signature.algorithm": "RSA_SHA256"
      "saml.client.signature": "true"
      "saml.allow.ecp.flow": "false"
      "saml.assertion.signature": "false"
      "saml.encrypt": "false"
      "saml.server.signature": "true"
      "saml.artifact.binding.identifier": "HC5ftXuLr0FUnJUosZarVSvzZh0="
      "saml.artifact.binding": "false"
      "saml_force_name_id_format": "false"
      "saml.authnstatement": "true"
      "display.on.consent.screen": "false"
      "saml_name_id_format": "username"
      "saml.onetimeuse.condition": "false"
      "saml_signature_canonicalization_method": "http://www.w3.org/2001/10/xml-exc-c14n#"
    authenticationFlowBindingOverrides: {}
    fullScopeAllowed: false
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: "acme-saml-email"
        protocol: saml
        protocolMapper: saml-user-property-mapper
        consentRequired: false
        config:
          attribute.nameformat: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
          user.attribute: email
          friendly.name: email
          attribute.name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      - name: "acme-saml-lastname"
        protocol: saml
        protocolMapper: saml-user-property-mapper
        consentRequired: false
        config:
          attribute.nameformat: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
          user.attribute: lastName
          friendly.name: surname
          attribute.name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
      - name: "acme-saml-firstname"
        protocol: saml
        protocolMapper: saml-user-property-mapper
        consentRequired: false
        config:
          attribute.nameformat: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
          user.attribute: firstName
          friendly.name: givenName
          attribute.name: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
    defaultClientScopes: []
    optionalClientScopes: []

  - clientId: acme-api-gateway
    protocol: openid-connect
    name: Acme API Gateway
    description: "Acme API Gateway can translate API keys to access tokens via token-exchange"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    secret: "$(env:ACME_CLIENT_EXAMPLES_CLIENT_SECRET:-secret)"
    defaultClientScopes:
      - "email"
      - "profile"
      - "roles"
    optionalClientScopes:
      - "phone"

users:
  - username: employee
    email: employee@local
    firstName: Erik
    lastName: Employee
    enabled: true
    attributes:
      locale: ["en"]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false

  - username: tester
    email: tester@local
    firstName: Theo
    lastName: Tester
    enabled: true
    attributes:
      locale: ["en"]
      phoneNumber: ["+49178111222333"]
      phoneNumberVerified: ["true"]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false

  - username: api-user-42
    enabled: true
    realmRoles: []
    clientRoles:
      account: []
    credentials:
      - type: password
        userLabel: initial
        value: "7FTt1Q0PG5yv3YqaZGhEB19KIollpNFurA"
        temporary: false