realm: acme-auth0
enabled: true
displayName: Acme Auth0
displayNameHtml: Acme Auth0
loginWithEmailAllowed: true
loginTheme: internal
internationalizationEnabled: true
supportedLocales: ["en","de"]
defaultLocale: "en"
resetPasswordAllowed: true
accountTheme: keycloak.v2
adminTheme: keycloak
emailTheme: keycloak
sslRequired: $(env:SSL_REQUIRED:-EXTERNAL)

identityProviders:
  - alias: "auth0"
    displayName: "Acme Auth0 Login"
    providerId: "oidc"
    enabled: true
    updateProfileFirstLoginMode: on
    trustEmail: true
    storeToken: false
    addReadTokenRoleOnCreate: false
    authenticateByDefault: false
    linkOnly: false
    firstBrokerLoginFlowAlias: "first broker login"
    #    postBrokerLoginFlowAlias: "Custom Post Broker Login"
    config:
      guiOrder: "1000"
      issuer: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/"
      tokenUrl: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/oauth/token"
      jwksUrl: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/.well-known/jwks.json"
      userInfoUrl: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/userinfo"
      authorizationUrl: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/authorize"
      logoutUrl: "https://$(env:ACME_AUTH0_DOMAIN:-dummy.eu).auth0.com/v2/logout"
      clientId: "$(env:ACME_AUTH0_CLIENT_ID:-dummy)"
      clientSecret: "$(env:ACME_AUTH0_CLIENT_SECRET:-secret)"
      clientAuthMethod: "client_secret_post"
      defaultScope: "openid profile email"
      loginHint: "true"
      backchannelSupported: "true"
      validateSignature: "true"
      useJwksUrl: "true"
      syncMode: "FORCE"
      pkceEnabled: "true"
      pkceMethod: "S256"

browserFlow: "browser-auth0"

authenticationFlows:
  - alias: "browser-auth0"
    description: "Custom browser flow with Auth0 as default IdP"
    providerId: basic-flow
    builtIn: false
    topLevel: true
    authenticationExecutions:
      - authenticator: auth-cookie
        requirement: ALTERNATIVE
      - authenticator: identity-provider-redirector
        requirement: ALTERNATIVE
        authenticatorConfig: "default-to-auth0"

authenticatorConfig:
  - alias: "default-to-auth0"
    config:
      defaultProvider: "auth0"
