realm: acme-demo
enabled: true
displayName: Acme Demo
displayNameHtml: Acme Demo
loginWithEmailAllowed: true
loginTheme: internal
resetPasswordAllowed: true
#accountTheme: keycloak.v2
#adminTheme: keycloak
#emailTheme: keycloak
sslRequired: $(env:SSL_REQUIRED:-EXTERNAL)

clients:
  - clientId: app-minispa
    protocol: openid-connect
    name: Acme Account Console
    description: "Acme Account Console Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false
    #    attributes: { }
    fullScopeAllowed: true
    rootUrl: "$(env:APPS_FRONTEND_URL_MINISPA)"
    baseUrl: "/?realm=acme-demo&show=profile,settings,apps,security,logout,token,idToken,revoke"
    adminUrl: ""
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "basic"
      - "email"
      - "roles"
      - "profile"
    optionalClientScopes:
      - "phone"
    attributes:
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"
  - id: acme-standard-client-1
    clientId: acme-standard-client
    protocol: openid-connect
    name: Client with Standard Flow
    description: "Standard Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    secret: acme-standard-client-1-secret
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/acme-standard-client/login*"
      - "https://flowsimulator.pragmaticwebsecurity.com"
    webOrigins:
      - "+"
    attributes:
#      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - id: acme-public-client-1
    clientId: acme-public-client-1
    protocol: openid-connect
    name: Client with Standard Flow
    description: "Public Client Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/acme-public-client/login*"
      - "https://flowsimulator.pragmaticwebsecurity.com"
    webOrigins:
      - "+"
    attributes:
      #      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - id: acme-implicit-client-1
    clientId: acme-implicit-client
    protocol: openid-connect
    name: Client with Implicit Grant
    description: "Implicit Client Description v2"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    implicitFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/acme-implcit-client/oauth/callback"

  - id: acme-direct-access-client-1
    clientId: acme-direct-access-client
    protocol: openid-connect
    name: Standard Client with ROPC Grant
    description: "Direct Access Grant Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    secret: acme-direct-access-client-1-secret
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/acme-direct-access-client-1/login*"
      - "https://flowsimulator.pragmaticwebsecurity.com/*"

  - id: acme-service-client-1
    clientId: acme-service-client
    protocol: openid-connect
    name: Standard Client with Client Credentials Grant
    description: "Service Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    secret: acme-service-client-1-secret
    fullScopeAllowed: false

  - id: acme-device-client
    clientId: acme-device-client
    protocol: openid-connect
    name: Client with Device Flow Grant
    description: "Device Flow Grant Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    attributes:
      #"use.refresh.tokens": "false"
      "use.refresh.tokens": "true"
      "oauth2.device.authorization.grant.enabled": "true"
    redirectUris: []

users:
  - username: tester
    email: test@local.test
    firstName: Theo
    lastName: Tester
    enabled: true
    attributes:
      locale: [ "de" ]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false
