realm: acme-internal
enabled: true
displayName: Acme Internal
displayNameHtml: Acme Internal
loginWithEmailAllowed: true
loginTheme: internal
resetPasswordAllowed: true
accountTheme: keycloak.v2
adminTheme: keycloak
emailTheme: keycloak
sslRequired: ${env:SSL_REQUIRED:-EXTERNAL}
browserFlow: "Browser Identity First"

eventsListeners:
  - "jboss-logging"
  - "acme-audit-listener"
eventsEnabled: true
# 120 days
eventsExpiration: 10368000
# enabledEventTypes: [ "SEND_RESET_PASSWORD", "UPDATE_CONSENT_ERROR", "GRANT_CONSENT", ... ]
adminEventsEnabled: false
adminEventsDetailsEnabled: false

smtpServer:
  replyToDisplayName: "Acme Employee Support"
  port: 1025
  host: mailhog
  replyTo: "no-reply@localhost"
  from: "acme-internal-sso@local"
  fromDisplayName: "Acme Employee Account"

clientScopes:
  - name: acme.profile
    description: Acme Profile Access
    protocol: openid-connect
  - name: acme.ageinfo
    description: Acme Profile AgeInfo
    protocol: openid-connect
    protocolMappers:
      - name: "Acme: AgeInfo"
        protocol: openid-connect
        protocolMapper: oidc-acme-ageinfo-mapper
        consentRequired: false
        config:
          userinfo.token.claim: "true"
          id.token.claim: "true"
          access.token.claim: "false"

  - name: acme.api
    description: Acme API Access
    protocol: openid-connect

clients:
  - clientId: app-minispa
    protocol: openid-connect
    name: App Mini SPA
    description: "App Mini SPA Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
#    attributes: { }
    fullScopeAllowed: false
    rootUrl: "${env:APPS_FRONTEND_URL_MINISPA}"
    baseUrl: "/?realm=acme-internal"
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
      - "acme.profile"
    optionalClientScopes:
      - "phone"

  - clientId: acme_internal_idp_broker
    protocol: openid-connect
    name: Acme Internal Broker
    description: "Acme Internal IdP Broker Client"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    fullScopeAllowed: false
    secret: "${env:ACME_APPS_INTERNAL_IDP_BROKER_SECRET:-secret}"
    redirectUris:
      - "${env:KEYCLOAK_FRONTEND_URL}/realms/acme-apps/broker/idp-acme-internal/endpoint/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"

  - clientId: test-client
    protocol: openid-connect
    name: Test Client
    description: "Test Client Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    rootUrl: "${env:APPS_FRONTEND_URL_MINISPA}"
    baseUrl: "/?realm=acme-internal&client_id=test-client"
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "phone"
      - "acme.profile"
      - "acme.ageinfo"

authenticationFlows:
## Identity First Browser Login Flow
  - alias: "Browser Identity First"
    description: "This flow implements the Identity First pattern"
    providerId: basic-flow
    builtIn: false
    topLevel: true
    authenticationExecutions:
      - authenticator: auth-cookie
        requirement: ALTERNATIVE
        priority: 1010
      - authenticator: identity-provider-redirector
        requirement: ALTERNATIVE
        priority: 1020
      - requirement: ALTERNATIVE
        priority: 1030
        flowAlias: "Identity Forms"
        autheticatorFlow: true

  - alias: "Identity Forms"
    description: "Sub-Flow to ask user for username an password"
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - requirement: REQUIRED
        authenticator: auth-username-form
        priority: 2010
      - requirement: REQUIRED
        authenticator: auth-password-form
        priority: 2020
      - requirement: CONDITIONAL
        autheticatorFlow: true
        flowAlias: "2FA Forms"
        priority: 2030

  - alias: "2FA Forms"
    description: "Sub-Flow to ask user for 2FA"
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: conditional-user-configured
        requirement: REQUIRED
        priority: 3010
      - authenticator: auth-otp-form
        requirement: REQUIRED
        priority: 3020

# Manual default realmRoles assigned due too keycloak-config-cli bug, remove when issue has been fixed https://github.com/adorsys/keycloak-config-cli/issues/451
users:
  - username: employee
    email: employee@local
    firstName: Erik
    lastName: Employee
    enabled: true
    attributes:
      locale: ["de"]
    credentials:
      - type: password
        value: test
        temporary: false
    realmRoles:
      - default-roles-acme-internal

  - username: tester
    email: tester@local
    firstName: Theo
    lastName: Tester
    enabled: true
    attributes:
      locale: ["de"]
    credentials:
      - type: password
        value: test
        temporary: false
    realmRoles:
      - default-roles-acme-internal
