realm: acme-ops
enabled: true
displayName: Acme Operations
displayNameHtml: Acme Operations
loginWithEmailAllowed: true
loginTheme: internal
internationalizationEnabled: true
supportedLocales: ["en","de"]
defaultLocale: "en"
resetPasswordAllowed: true
accountTheme: keycloak.v2
adminTheme: keycloak
emailTheme: keycloak
sslRequired: $(env:SSL_REQUIRED:-EXTERNAL)
roles:
  client:
    grafana:
      - name: "Viewer"
        description: "Allowed to read grafana"
        composite: false
        clientRole: true
      - name: "Editor"
        description: "Allowed to edit grafana"
        composite: false
        clientRole: true
      - name: "Admin"
        description: "Allowed to administrate grafana"
        composite: false
        clientRole: true

clientScopes:
  - name: "roles"
    description: OpenID Connect scope for add user roles to the access token
    protocol: openid-connect
    attributes:
      include.in.token.scope: 'false'
      display.on.consent.screen: 'true'
      consent.screen.text: "${rolesScopeConsentText}"
    protocolMappers:
      - name: realm roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          user.attribute: foo
          access.token.claim: 'true'
          claim.name: realm_access.roles
          jsonType.label: String
          multivalued: 'true'
      - name: audience resolve
        protocol: openid-connect
        protocolMapper: oidc-audience-resolve-mapper
        consentRequired: false
      - name: client roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
        consentRequired: false
        config:
          access.token.claim: 'true'
          id.token.claim: 'false'
          userinfo.token.claim: 'true'
          claim.name: resource_access.${client_id}.roles
          jsonType.label: String
          multivalued: 'true'

clients:
  - clientId: grafana
    protocol: openid-connect
    name: Client for grafana
    description: "Secure grafana"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    secret: grafana-secret
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost:3000/login*"

users:
  - username: aadmina
    email: admin@local.test
    firstName: Adele
    lastName: Admina
    enabled: true
    credentials:
      - type: password
        value: test
        temporary: false
    clientRoles:
      grafana:
        - "Admin"