micronaut:
  application:
    name: backendApiMicronaut
  ssl:
    enabled: true
    keyStore:
      path: file:config/stage/dev/tls/acme.test+1.p12 # (1)
      password: changeit # (2)
      type: PKCS12
  security:
    authentication: bearer
    token:
      name-key: "preferred_username"
      jwt:
        signatures:
          jwks:
            keycloak:
              url: "${micronaut.security.token.jwt.claims-validators.issuer}/protocol/openid-connect/certs"
        claims-validators:
          issuer: "https://id.acme.test:8443/auth/realms/acme-internal"
          expiration: true
          subject-not-null: true
      #          audience: ""

  server:
    ssl:
      port: 4953
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - https://apps.acme.test:4443

netty:
  default:
    allocator:
      max-order: 3
