realm: custom
enabled: true
displayName: Custom
displayNameHtml: <div class="kc-logo-text"><span>Custom</span></div>
loginWithEmailAllowed: true
loginTheme: custom
accountTheme: keycloak.v2
adminTheme: keycloak
emailTheme: keycloak
sslRequired: ${env:SSL_REQUIRED:-EXTERNAL}
browserFlow: "Browser Identity First"

clientScopes:
  - name: custom.profile
    description: Custom Profile Access
    protocol: openid-connect
  - name: custom.api
    description: Custom API Access
    protocol: openid-connect
  - name: custom.ageinfo
    description: Age Information
    protocol: openid-connect

clients:
  - clientId: app-minispa
    protocol: openid-connect
    name: App Mini SPA
    description: "App Mini SPA Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
#    attributes: { }
    fullScopeAllowed: false
    rootUrl: "http://localhost:4000"
    baseUrl: "/?realm=custom"
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "custom.profile"
      - "custom.ageinfo"
      - "phone"

  - clientId: test-client
    protocol: openid-connect
    name: Test Client
    description: "App Mini SPA Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    rootUrl: "http://localhost:4000"
    baseUrl: "/?realm=custom"
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
      - "profile"
    optionalClientScopes:
      - "custom.profile"
      - "custom.ageinfo"
      - "custom.api"
      - "phone"

authenticationFlows:
  - alias: "Browser Identity First"
    description: "This flow implements the Identity First pattern"
    providerId: basic-flow
    builtIn: false
    topLevel: true
    authenticationExecutions:
      - authenticator: auth-cookie
        requirement: ALTERNATIVE
        priority: 1010
      - authenticator: identity-provider-redirector
        requirement: ALTERNATIVE
        priority: 1020
      - requirement: ALTERNATIVE
        priority: 1030
        flowAlias: "Identity Forms"
        autheticatorFlow: true

  - alias: "Identity Forms"
    description: "Sub-Flow to ask user for username an password"
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - requirement: REQUIRED
        authenticator: auth-username-form
        priority: 2010
      - requirement: REQUIRED
        authenticator: auth-password-form
        priority: 2020
      - requirement: CONDITIONAL
        autheticatorFlow: true
        flowAlias: "2FA Forms"
        priority: 2030

  - alias: "2FA Forms"
    description: "Sub-Flow to ask user for 2FA"
    providerId: basic-flow
    topLevel: false
    builtIn: false
    authenticationExecutions:
      - authenticator: conditional-user-configured
        requirement: REQUIRED
        priority: 3010
      - authenticator: auth-otp-form
        requirement: REQUIRED
        priority: 3020

users:
  - username: tester
    email: tester@local
    firstName: Theo
    lastName: Tester
    enabled: true
    attributes:
      locale:
        - "de"
    credentials:
      - type: password
        value: test
        temporary: false