services:

  acme-keycloak-1:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: https://id.acme.test:1443/auth
    # IntelliJ currently does not support the depends_on condition syntax
    depends_on:
      acme-keycloak-db:
        condition: service_healthy


  acme-keycloak-2:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: https://id.acme.test:1443/auth
    # IntelliJ currently does not support the depends_on condition syntax
    depends_on:
      acme-keycloak-db:
        condition: service_healthy

  acme-keycloak-db:
    extends:
      file: ../docker-compose.yml
      service: acme-keycloak-db

  acme-haproxy-lb:
    build: .
    volumes:
      # relative paths needs to be relative to the docker-compose cwd.
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z
#      - ../../../../config/stage/dev/tls/acme.test+1.pem:/etc/haproxy/haproxy.crt.pem:z
#      - ../../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/haproxy/haproxy.crt.pem.key:z
# - ../run/haproxy/run:/var/run:z
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    command:
      - "-f"
      - "/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "1443:1443"
    depends_on:
      - acme-keycloak-1
      - acme-keycloak-2
