services:
  acme-opa:
    image: openpolicyagent/opa:0.46.1-rootless
    command:
      - run
      - --server
      - --set
      - "decision_logs.console=true"
    ports:
      - "18181:8181"
      - "18182:8182"
