services:
  acme-keycloak-provisioning:
    image: quay.io/adorsys/keycloak-config-cli:v4.7.0-17.0.0
    env_file:
# generated via start.java
      - ./../../../generated.env.tmp
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      IMPORT_PATH: "/config"
      IMPORT_FORCE: "false"
      IMPORT_VARSUBSTITUTION: "true"
      IMPORT_VALIDATE: "true"

# See https://github.com/adorsys/keycloak-config-cli#log-level
#      LOGGING_LEVEL_KEYCLOAKCONFIGCLI: "debug"

    volumes:
      - ../../../config/stage/dev/realms:/config:z