services:
  acme-keycloak:
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
      - ./keycloak-tls.env
    volumes:
      # This configures the key and certificate for HTTPS.
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/https/tls.crt:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/etc/x509/https/tls.key:z
      # Allow TLS connection to ourself, this is necessary for cross realm Identity Brokering
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/ca/tls.crt:z
      # Configure truststore for out-going https requests
      - ../../../config/stage/dev/tls/acme.test+1.p12:/opt/keycloak/conf/truststore.p12:z
      # make calls to external systems that use the tls certs
      - ${CA_ROOT_CERT:-}:/etc/x509/ca/tls-root.crt:z

  acme-account-console:
    image: httpd:2.4.51-bullseye
    volumes:
      - ../../../apps/acme-account-console:/usr/local/apache2/htdocs/acme-account:z
      - ../../../apps/acme-greetme:/usr/local/apache2/htdocs/acme-greetme:z
      - ../../../config/stage/dev/tls/acme.test+1.pem:/usr/local/apache2/conf/server.crt:z
      - ../../../config/stage/dev/tls/acme.test+1-key.pem:/usr/local/apache2/conf/server.key:z
    ports:
      - "4000:80"
      - "4443:443"
    command:
      - /bin/sh
      - -c
      - |
        echo 'ServerName apps.acme.test' >> conf/httpd.conf 
        sed -i -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' conf/httpd.conf
        sed -i -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' conf/httpd.conf 
        sed -i -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' conf/httpd.conf 
        exec httpd-foreground
