services:
  acme-keycloak-provisioning:
    image: quay.io/adorsys/keycloak-config-cli:v4.5.0-16.0.0
    env_file:
# generated via start.java
      - ./../../../generated.env.tmp
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      IMPORT_PATH: "/config"
      IMPORT_FORCE: "false"
      IMPORT_VARSUBSTITUTION: "true"
    volumes:
      - ../../../config/stage/dev/realms:/config:z