services:
  acme-opa:
    image: openpolicyagent/opa:0.60.0
    platform: linux/amd64
    command:
      - run
      - --server
      - --set
      - "decision_logs.console=true"
      # Watch for changes in policy folder
      - "--watch"
      - "/policies"
    volumes:
      - ../../../config/stage/dev/opa/iam:/policies/iam:z
      - ../../../config/stage/dev/opa/policies/keycloak:/policies/keycloak:z
    ports:
      - "18181:8181"
