services:
  acme-keycloak:
    #image: quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

    build:
      context: "./keycloakx"
      dockerfile: "./Dockerfile"

    #    user: "${USER}:${GROUP}"
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
      KC_DB: "h2-file"
      KC_HTTP_RELATIVE_PATH: "/auth"

      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"

    # Enable remote debugging
      DEBUG: "true"
      DEBUG_PORT: "*:8787"

      # Append additional JVM Options besides the default JVM_OPTS
      # See: https://github.com/keycloak/keycloak/blob/main/distribution/server-x-dist/src/main/content/bin/kc.sh#L66
      JAVA_OPTS_APPEND: "-XX:+UseStringDeduplication"

      # Allow access via visualvm and jmc (remote jmx connection to localhost 8790 without ssl)
      # see https://docs.oracle.com/en/java/javase/11/management/monitoring-and-management-using-jmx-technology.html#GUID-D4CBA2D6-2E24-4856-A7D8-62B3DFFB76EA
      JAVA_TOOL_OPTIONS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8790 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/opt/keycloak/conf/jmxremote.password -Dcom.sun.management.jmxremote.ssl=false -XX:FlightRecorderOptions=stackdepth=256"
    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

    command:
      - "--verbose"
      - "start-dev"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--metrics-enabled=true"
      - "--cache=local"
      - "--proxy=passthrough"
#      - "--config-file=/opt/keycloak/conf/keycloak.properties"
#      - "--verbose"
    #      - "-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog"
    extra_hosts:
      # 172.17.0.1 is host.docker.internal
      - "id.acme.test:172.17.0.1"
      - "apps.acme.test:172.17.0.1"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "127.0.0.1:8790:8790"
      - "127.0.0.1:8787:8787"
    volumes:
      - ../../../keycloak/themes/apps:/opt/keycloak/themes/apps:z
      - ../../../keycloak/themes/internal:/opt/keycloak/themes/internal:z
      - ../../../keycloak/themes/internal-modern:/opt/keycloak/themes/internal-modern:z
      - ../../../keycloak/config/profile.properties:/opt/keycloak/conf/profile.properties:z
      - ../../../keycloak/config/jmxremote.password:/opt/keycloak/conf/jmxremote.password:ro
      - ../../../keycloak/imex:/opt/keycloak/imex:z
      - ./run/keycloakx/data:/opt/keycloak/data:z
      - ./run/keycloakx/logs:/opt/keycloak/logs:z
      - ./run/keycloakx/perf:/opt/keycloak/perf:z
      - ./keycloakx/keycloak_default.properties:/opt/keycloak/conf/keycloak.properties:z
      - ../../../keycloak/extensions/target/extensions.jar:/opt/keycloak/providers/extensions.jar:z
# Add third-party extensions
#      - ./keycloak-ext/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:/opt/jboss/keycloak/providers/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:z
      - ./keycloak-ext/keycloak-home-idp-discovery-16.0.0.jar:/opt/jboss/keycloak/providers/keycloak-home-idp-discovery-16.0.0.jar:z
# Add Keycloak.X specific extensions
      - ../../../keycloak/extensionsx/target/extensionsx.jar:/opt/keycloak/providers/extensionsx.jar:z
