services:
  acme-keycloak-db:
    build:
      context: "../../../config/stage/dev/tls"
      dockerfile: "../../../../deployments/local/dev/postgresql/Dockerfile"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    command:
# Certificates are added in the Dockerfile with the proper permissions for postgresql
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/server.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/server.key"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "max_connections=200"
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./run/postgres/data:/var/lib/postgresql/data:z

  acme-keycloak:
    env_file:
      - ./keycloak-db.env
    environment:

      # default 0
      QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE: 64

      # default 0
      QUARKUS_DATASOURCE_JDBC_MIN_SIZE: 64
      # default 20, see https://quarkus.io/version/2.13/guides/all-config#quarkus-agroal_quarkus.datasource.jdbc.max-size
      QUARKUS_DATASOURCE_JDBC_MAX_SIZE: 64
      # default 20, see https://quarkus.io/version/2.13/guides/all-config#quarkus-vertx_quarkus.vertx.worker-pool-size
      QUARKUS_VERTX_WORKER_POOL_SIZE: 64

      # default 5 seconds, see https://quarkus.io/version/2.13/guides/all-config#quarkus-agroal_quarkus.datasource.jdbc.acquisition-timeout
      QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT: 20

      KC_DB: postgres
      # See postgres JDBC URL parameters: https://jdbc.postgresql.org/documentation/head/connect.html
      KC_DB_URL_PROPERTIES: "?ApplicationName=keycloak&ssl=true&sslmode=verify-ca&sslrootcert=/etc/x509/ca/tls.crt"
    volumes:
      # Allow TLS connection to ourself, this is necessary for cross realm Identity Brokering
      - ../../../config/stage/dev/tls/acme.test+1.pem:/etc/x509/ca/tls.crt:z
# IntelliJ currently does not support the depends_on condition syntax
    depends_on:
      acme-keycloak-db:
        condition: service_healthy
