services:
  acme-keycloak-db:
    build:
      context: "../../../config/stage/dev/tls"
      dockerfile: "../../../../deployments/local/dev/oracle/Dockerfile"
    environment:
      ORACLE_PASSWORD: 'secret'
      APP_USER: 'keycloak'
      APP_USER_PASSWORD: 'keycloak'
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - keycloak-data-oracle1:/opt/oracle/oradata:z

  acme-keycloak:
    environment:
      KC_DB: oracle
      KC_DB_DRIVER: "oracle.jdbc.OracleDriver"
      KC_DB_URL: "jdbc:oracle:thin:@acme-keycloak-db:1521/FREEPDB1"
      KC_TRANSACTION_XA_ENABLED: "false"
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'keycloak'
    depends_on:
      acme-keycloak-db:
        condition: service_healthy

volumes:
  keycloak-data-oracle1:
    name: keycloak-data-oracle1
