services:
  acme-keycloak:
    #image: quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

    build:
      context: "./keycloakx"
      dockerfile: "./Dockerfile"

    #    user: "${USER}:${GROUP}"
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
#      KEYCLOAK_USER: "admin"
#      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "h2"
      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"

# Exposes Metrics via http://localhost:9990/metrics
      KEYCLOAK_STATISTICS: all
      DEBUG_MODE: "true"
      DEBUG_PORT: "*:8787"

#      KEYCLOAK_IMPORT: "/opt/jboss/imex/custom-realm.json"
# use `docker-compose --env-file custom-keycloak.env up` to populate the KEYCLOAK_CONFIG_FILE variable.
    command:
      - "--http-port=8080"
      - "--auto-config"
      - "--http-enabled=true"
#      - "-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog"
    extra_hosts:
      # 172.17.0.1 is host.docker.internal
      - "id.acme.test:172.17.0.1"
      - "apps.acme.test:172.17.0.1"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "127.0.0.1:8787:8787"
    volumes:
      - ../../../keycloak/themes/apps:/opt/jboss/keycloak/themes/apps:z
      - ../../../keycloak/themes/internal:/opt/jboss/keycloak/themes/internal:z
      - ../../../keycloak/themes/internal-modern:/opt/jboss/keycloak/themes/internal-modern:z
      - ../../../keycloak/config/profile.properties:/opt/jboss/keycloak/conf/profile.properties:z
      - ../../../keycloak/imex:/opt/jboss/imex:z
# This will exposes *.sh and *.cli startup scripts that are executed by Keycloak.
      - ./run/keycloakx/data:/opt/jboss/keycloak/data:z
      - ./run/keycloakx/logs:/opt/jboss/keycloak/logs:z
      - ./run/keycloakx/perf:/opt/jboss/keycloak/perf:z
      - ../../../keycloak/extensions/target/extensions.jar:/opt/jboss/keycloak/providers/extensions.jar:z
