services:
  mailhog:
    # Web Interface: http://localhost:1080/#
    # Web API: http://localhost:1080/api/v2/messages
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    logging:
      driver: none
    ports:
      - "1080:8025"
      - "1025:1025"

  acme-account-console:
    image: httpd:2.4.51-bullseye
    volumes:
      - ../../../apps/acme-account-console:/usr/local/apache2/htdocs/acme-account:z
      - ../../../apps/acme-greetme:/usr/local/apache2/htdocs/acme-greetme:z
    ports:
      - "4000:80"
      - "4443:443"
