services:
  # Web Interface: http://localhost:1080/mail
  # Web API: https://github.com/maildev/maildev/blob/master/docs/rest.md
  mail:
    image: maildev/maildev:2.1.0 #@sha256:57e0b96fefb5dfeda8b39fb04c666ee7eef7be899ac8ea0e4d983bb0ea64aaff
    environment:
      MAILDEV_BASE_PATHNAME: "/mail"
    ports:
      - "1080:1080"
      - "1025:1025"

  acme-account-console:
    image: httpd:2.4.51-bullseye
    volumes:
      - ../../../apps/acme-account-console:/usr/local/apache2/htdocs/acme-account:z
      - ../../../apps/acme-greetme:/usr/local/apache2/htdocs/acme-greetme:z
      - ../../../apps/site:/usr/local/apache2/htdocs/site:z
    ports:
      - "4000:80"
      - "4443:443"

  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - '6379:6379'
    #  --requirepass redispass
    command: redis-server --save 20 1 --loglevel warning

