services:
  acme-keycloak-provisioning:
    image: quay.io/adorsys/keycloak-config-cli:v4.2.1-rc0-15.0.1
    env_file:
      - ./../../../generated.env.tmp
#      - ./keycloak-common.env
#      - ./keycloak-http.env
#      - ./keycloak-provisioning.env
    environment:
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      IMPORT_PATH: "/config"
      IMPORT_FORCE: "false"
      IMPORT_VARSUBSTITUTION: "true"
    volumes:
      - ../../../config/stage/dev/realms:/config:z