services:

  database:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - 25432:5432
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      dockerfile: ./keycloak/Dockerfile
    command: start-dev
    env_file: .env
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'

      # Keycloak DB
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd

      KC_LOG_LEVEL: INFO,com.acme.iam.keycloak:debug

      KC_FEATURES: preview

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/cert-key.pem

      KC_HOSTNAME: id.acme.test
      KC_PROXY: edge

    ports:
      - "8080:8080"
      - "8443:8443"
      - "8787:8787"
    volumes:
      - ./keycloak/providers:/opt/keycloak/providers
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak/conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties
      - ./config/certs/keycloak-cert.pem:/opt/keycloak/conf/certs/cert.pem
      - ./config/certs/keycloak-cert-key.pem:/opt/keycloak/conf/certs/cert-key.pem

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs/acme.test-cert.pem:/etc/tls/cert.pem
      - ./config/certs/acme.test-cert-key.pem:/etc/tls/cert-key.pem
      - ./config/certs/rootCA.pem:/etc/tls/rootCA.pem
    ports:
      - "443:443"
    depends_on:
      - keycloak

  mailserver:
    # Web Interface: http://localhost:1080/mail
    # Web API: https://github.com/maildev/maildev/blob/master/docs/rest.md
    image: maildev/maildev:2.1.0@sha256:57e0b96fefb5dfeda8b39fb04c666ee7eef7be899ac8ea0e4d983bb0ea64aaff
    environment:
      MAILDEV_BASE_PATHNAME: "/mail"
    ports:
      - "1080:1080" #web ui
      - "1025:1025" #smtp
    networks:
      - backend

volumes:
  keycloak-db-data:
    name: keycloak-db-data